## $ \text{Cross Entropy Loss} $ 

`CrossEntropyLoss`는 내부적으로 `LogSoftmax`와 `NLLLoss`가 결합된 함수다. 

`LogSoftmax`는 Softmax 함수를 사용한 후 Log 함수를 적용한 것을 의미하고, `NLLLoss`는 Negative Log Likelihood를 의미한다. 

$$ l_n = -w_{y_n} \log \frac{\exp(x_{n, y_n})}{\sum^C_{c=1}\exp(x_{n,c})} $$

In [2]:
import torch
import torch.nn as nn 

In [17]:
CE_loss = nn.CrossEntropyLoss()
inputs = torch.randn(3, 5, requires_grad=True)
label_target = torch.empty(3, dtype=torch.long).random_(5)
output = CE_loss(inputs, label_target)


print(inputs)
print(label_target)

print(output)

m = nn.Sigmoid()
output = CE_loss(m(inputs), label_target)
print(output)

tensor([[ 0.0893,  0.6787,  1.0965, -0.8594,  1.0114],
        [-1.6852, -0.4836,  0.8726,  0.5809, -1.7477],
        [-2.4419,  1.0551, -1.0063,  0.2250,  0.1060]], requires_grad=True)
tensor([0, 1, 4])
tensor(1.9633, grad_fn=<NllLossBackward0>)
tensor(1.6332, grad_fn=<NllLossBackward0>)


In [8]:
# Example of target with class probabilities
inputs = torch.randn(3, 5, requires_grad=True)
prob_target = torch.randn(3, 5).softmax(dim=1)
output = CE_loss(inputs, prob_target)
output.backward()

tensor([4, 3, 2])